feedback = (input("enter your feedbak:"))
print("customer feedback report".upper().center(70))
print("=============================")
print("feedback:",feedback.title())

print("feedback summary")
print("total word count:".title(),len(feedback.split()))
print("total character count:".title(),len(feedback))
print("total space count:".title(),feedback.count(""))
print("total exlamation count:".title(),feedback.count("!"))
print("/n=================================/n")

print("formated feedback:".lstrip())
print("/n")
print("uppercase feedback:",feedback.upper())
print("lowercase feedback:",feedback.lower())
print("title feedback:",feedback.title())
print("captalize feedback:",feedback.capitalize())
print("swapcase feedback:",feedback.swapcase())
print("/n====================================/n")
print("professional feedback:".capitalize())
print("/n")
print("word split=",feedback.split())
print("thank you for your valuable feedback".center(70).upper())